### ISSUE TITLE
error when querying p279star file - 02-kg-profiling.ipynb

### ISSUE THREAD

**Issue by versant2612** [usc-isi-i2/kgtk-notebooks#3]
When I execute the following command inside Colab environment, this error comes up

kgtk("""
    query -i p279star
        --match '(class)-[:P279star]->(super_class)'
        --return 'count(distinct super_class) as count_classes'
""")

[Errno 2] No such file or directory: '/content/p279star'

**Comment by saggu** [comment]
Related to #2 . I'll address it there. Closing
