### ISSUE TITLE
Unrealized dependency

### ISSUE THREAD

**Issue by aditya-malte** [usc-isi-i2/kgtk-notebooks#4]
This issue might be affecting specific versions of kgtk at a higher rate (specifically those that are not dependent on these dependencies and hence didn't install them beforehand)

Attempting to import the following libraries returns an error even when kgtk is installed:
* gensim
* papermill

Could be a good idea to include a very minimal requirements.txt file in this repo?

cc @filievski

**Comment by saggu** [comment]
@aditya-malte yes please, create a PR to this repo
